---
- name: Include host networking tasks
  ansible.builtin.include_tasks: network.yml
  when: proxmox_network_manage
  tags:
    - network

- name: Include firewall tasks
  ansible.builtin.include_tasks: firewall.yml
  when: proxmox_firewall_manage
  tags:
    - firewall

- name: Include VM template tasks
  ansible.builtin.include_tasks: template.yml
  when: proxmox_template_manage
  tags:
    - template

- name: Include VM tasks
  ansible.builtin.include_tasks: vm.yml
  when: proxmox_vm_manage
  tags:
    - vm
